deployment:
  branches:
    - testbranch # Specify the branch you want to track (e.g., 'testbranch')

  environments:
    - production:
        url: "https://i-scs.co.uk" # The URL of your site

  repositories:
    - https://github.com/kamaljameel/supply-chain-scs.git # Replace with your GitHub repository URL

  post_deploy:
    - git pull origin testbranch # Pull the latest changes from 'testbranch' after deployment
